import Head from "next/head";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import styles from "@/styles/Home.module.css";
import ImageComponent from "src/components/ImageComponent";
import HeaderComponent from "src/components/HeaderComponent";
import FooterComponent from "src/components/FooterComponent";
import FormComponent from "src/components/FormComponent";
import ButtonComponent from "src/components/ButtonComponent";
import imgCode from "src/assets/code2.png";
import imgCode2 from "src/assets/code3.png";
import imgCode3 from "src/assets/code1.png";
import imgCode4 from "src/assets/code4.png";
import imgCode5 from "src/assets/code5.png";
import reactLogo from "src/assets/react-logo.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>HTML vs. JSX</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${styles.main} ${inter.className} bg-black`}>
				<HeaderComponent srcImage={reactLogo} name="This is React" />

				<div className="container">
					<h1 id={styles.title} className="text-white fw-bold ms-2">
						HTML vs. JSX
					</h1>

					<div className={`${inter.className} container text-white`}>
						<p className="">
							Hypertext Markup Language (HTML) is the standard
							language for documents that determine the structure
							of a web page. Your code is either in HTML
							originally or compiles to it so browsers can read
							it. JSX, on the other hand, means JavaScript Syntax
							Extension or JavaScript XML as some like to put it.
							HTML and JSX are both used for creating web
							interfaces, but there are some differences between
							them.
						</p>
						<br />
						<h2 className="fw-bold">Syntax</h2>
						<p>
							In HTML, we write tags using
							<strong> angle brackets {"<>"}</strong>and use
							attributes to modify elements. JSX, on the other
							hand, allows us to write HTML-like syntax within
							JavaScript.
						</p>

						<ImageComponent srcImage={imgCode3} />

						<br />
						<br />
						<h2 className="fw-bold">Embedding Expressions</h2>
						<p>
							JSX provides a way to embed JavaScript expressions
							within curly braces <strong>{"{ }"}</strong>{" "}
							directly in the markup. This allows us to
							dynamically render values or execute functions.
						</p>
						<ImageComponent srcImage={imgCode2} />

						<br />
						<br />
						<h2 className="fw-bold">ClassName</h2>
						<p>
							To define class names and for attributes in JSX, you
							don't do it as class or for, since both are reserved
							keywords in JavaScript. You actually create class
							components with the class keyword. So, to define
							class names in JSX, you do it as "className" and for
							attributes for labels you write "HTMLFor":
						</p>

						<ImageComponent srcImage={imgCode} />

						<h2 className="fw-bold">Components</h2>
						<p>
							JSX allows us to define custom components using
							React. We can compose complex UIs by combining these
							components, which is not possible with HTML alone.
						</p>

						<ImageComponent srcImage={imgCode5} />
						<br />

						<h2 className="fw-bold">
							Write Inline Styles as Objects in JSX
						</h2>
						<p>
							To define inline styles for JSX, you write it as an
							object, with the properties in camelCase, the values
							in quotes, and then you pass it inline to the JSX.
							This means you have to open up a style attribute and
							use curly braces instead of quotes. This is opposed
							to HTML where you're free to define millions of
							styles right inside the opening tag without writing
							them as objects and putting them in quotes:
						</p>

						<ImageComponent srcImage={imgCode4} />
					</div>
				</div>

				<FormComponent formTitle="Contact Me" />

				<FooterComponent
					name="Lex Oxales"
					fbLink="https://www.facebook.com/lex.oxales"
					igLink="https://www.instagram.com/_jowsep_/"
					githubLink="https://github.com/ajoxales"
				/>
			</main>
		</>
	);
}
